import Head from 'next/head'
import Header from '@/components/header'
import Cardcontainer from '@/components/Cardcontainer'
import Subscribe from '@/components/Subscribe'
import Layout from '@/components/layout'
import { setSession } from '@/store/slices/authslice'
import { useDispatch } from 'react-redux'
import { useSession } from 'next-auth/react'
import { useEffect } from 'react'



export default function Home() {
  const dispatch=useDispatch()
  const {data:session}=useSession()

useEffect(()=>{
    dispatch(setSession(session))

},[session])

  return (
    <>
      <Head>
        <title>Ticket plug</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <Header />
      <Cardcontainer />
      <Subscribe />
      </Layout>
     </>
  )
}
